language: go
go:
  - stable

addons:
  apt:
    packages:
    - python-virtualenv

go_import_path: github.com/uber/ringpop-go

install:
  - go get -u github.com/Masterminds/glide
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - ./scripts/travis/get-thrift.sh
  - ./scripts/travis/get-thrift-gen.sh
  - ./scripts/travis/get-cram.sh
  - npm install -g tcurl@v4.22.2
  - make setup

env:
  - RUN="make test-unit test-race test-examples lint coveralls"
  - RUN="make test-integration"

matrix:
  fast_finish: true

script:
  - test/travis

cache:
  directories:
    - $HOME/.glide/cache
    - _venv

before_cache:  # glide touches ORIG_HEAD on `glide install`
  - find $HOME/.glide/cache -name ORIG_HEAD -exec rm {} \;
